[package]
name = "explore-events-3d"
version = "0.1.0"
authors = ["Todd Stellanova <tstellanova@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.18"
imageproc = "0.18.0"
image = "0.21.2"

kiss3d = "0.21.0"
#[dependencies.kiss3d]
#path = "../kiss3d"
